systemPrompt = "Summarize the given chunk of a meeting transcript in 300-400 characters. Focus on new information, key points, and developments. Note any unresolved issues or ongoing discussions. If the chunk continues a previous topic, briefly mention the context."
userPrompt = "Extract and concisely present the following from the transcript chunk: 1) New topics or developments, 2) Key decisions or action items (if any), 3) Unresolved issues or ongoing discussions. Include any available context indicators (e.g., time stamps, speaker changes). Prioritize new information over repetition."
exampleInputs = [
"John Smith: Thank you everyone for joining the call today. We have a few action items to cover in our call. First we will review the deck going over timeline of engagement, discuss data access requirements, look at architecture and then discuss next steps. Does that sound good?\nMary Hanson: Yes that worksLewis Johnson: Will this call be recorded\nJohn Smith: Sure thing, I can start that recording now.\nLewis Johnson: Thank you.\nJohn Smith: Okay so in this first slide we have the timeline.\nWe expect this engagement will take 3-4 weeks based on the scope of developments and deliverables. We have put together a team of our data scientists over in Germany to help out with our progress in this proof of concept.\nIt is a little late for them to join today due to timezone conflicts, but they will be on our next sync.Any questions?\nOk continuing on here is a look at the architecture diagram that was drafted up by Sally. Sally do you want to take it for here to explain it further?\nSally Micheals: Absolutely, Thanks John. Hi everyone so yes this is what I have drafted up based on the results of our in person workshop last week. We used all the stickies and mural board to show what the proposed architecture would look like….\nWith that, I can hand it back to you John\nJohn Smith:Any questions on anything Sally had just shared?\nLewis Johnson: Um yes. Quick question on the access to the environment. Would we be able to share this with our HR folks to test out?\nSally Michaels: Absolutely Lewis. Great question.\nWe will create different user roles with different access permissions and they will certainly be able to join our retrospective calls and share what progress they have made.\nLewis Johnson: OK great, thank you.\nJohn  Smith: Any other questions?\nOk if there are no other questions I think we can move on to what the next steps are both from our team and the CVSH team.\nOn our end, we will finish setting up environment access and user permissions and get those to your team immediately.\nCVS team, we will need a data dictionary documenting how you want us to create the sample data for the pilot. Once you send that over, Max, our Solution architect, will be able to create some synthetic data and load that into the platform.\nWe have our following session scheduled for Monday. Mary or Lewis, do you think that will be enough time for you to get us that information by Thursday?",
"[00:30:45] Emily: Any updates on the client feedback from last week?\nAlex: Still waiting on responses from two major clients.\nEmily: Okay, keep following up. Let's revisit this in our next meeting.",
"[00:45:00] Tom: Back to the budget discussion. Marketing, can you justify the increase?\nAna: Our Q4 campaign requires more resources.\nJim: But can we afford to reduce R&D spending?\nTom: We'll need more data. Ana, prepare a detailed proposal for next time."
]
exampleOutputs = [
"Meeting Recap: Met with CVS team to review project timeline, architecture, and data access. The team will meet next on Monday to review the action items from the call.\nAction Items:\n1. John's team: Complete setting up environment access and user permissions\n2. CVSH team: Provide data dictionary by Thursday for synthetic data creation\nNext Steps:\nMeeting on Monday to continue progressing project",
"[00:30:45] Ongoing: Client feedback from last week. Update: Responses pending from two major clients. Action item: Alex to continue follow-ups. To be revisited in next meeting.",
"[00:45:00] Continuation of budget discussion. New info: Q4 campaign driving marketing's requested increase. Concern raised about R&D budget reduction. Action item: Ana to prepare detailed proposal for next meeting. Unresolved: Final budget allocation decision."
]